/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CustomerController;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author llllllllll
 */
public class checkIn extends javax.swing.JFrame {
    private final CustomerController controller;
    /**
     * Creates new form checkIn
     */
    public checkIn() {
        initComponents();
        controller = new CustomerController(this);
        table_update();
        
        
    }
    
    
     public void table_update(){
      try {
            DefaultTableModel model = controller.getCustomerTableModel();
            jTable2.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtemaill = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        roomno = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btaddcheckin = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cbbed = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkin.png"))); // NOI18N
        jLabel1.setText("Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 301, 89));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 301, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 301, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nationality:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        txtnationality.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 301, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        cbgender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 301, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        txtemaill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtemaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 301, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Room Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 109, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 140, 124, -1));

        roomno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roomno.setText("Room No:");
        getContentPane().add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        txtRno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtRno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 125, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Check In Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, -1, -1));

        jTable2.setBackground(new java.awt.Color(255, 255, 102));
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Mobile no", "Natinality", "Gender", "Email", "Room Type", "Room no", "Bed", "Price", "Check InnDate"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 1390, 490));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close11.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 0, 50, -1));

        btaddcheckin.setBackground(new java.awt.Color(0, 0, 0));
        btaddcheckin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btaddcheckin.setForeground(new java.awt.Color(255, 255, 255));
        btaddcheckin.setText("Add Check In");
        btaddcheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddcheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btaddcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 740, -1, -1));

        btupdate.setBackground(new java.awt.Color(0, 0, 0));
        btupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btupdate.setForeground(new java.awt.Color(255, 255, 255));
        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 740, 140, -1));

        btdelete.setBackground(new java.awt.Color(0, 0, 0));
        btdelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btdelete.setForeground(new java.awt.Color(255, 255, 255));
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 740, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 300, -1));

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString(" yyyy/MM/dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 190, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Bed");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        cbbed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ac", "Non-AC" }));
        getContentPane().add(cbbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 140, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Address");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 290, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, -1, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 170, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chechinbk1.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btaddcheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddcheckinActionPerformed
        // TODO add your handling code here:
       try{
            String id = txtid.getText();
            String name = txtname.getText();
            String address = txtaddress.getText();
            String mobileNo = txtmobile.getText();
            String nationality = txtnationality.getText();
            String gender = (String) cbgender.getSelectedItem();
            String email = txtemaill.getText();
            String roomType = (String) jComboBox2.getSelectedItem();
            String roomNo = txtRno.getText();
            String bed = (String) cbbed.getSelectedItem();
            String price = txtprice.getText();
            Date checkinDate = null;
         if (jDateChooser1.getDate() != null) {
                checkinDate = new Date(jDateChooser1.getDate().getTime());
            }

            controller.addCustomer(id, name, address, mobileNo, nationality, gender, email, roomType, roomNo, bed, price, checkinDate);
            JOptionPane.showMessageDialog(this, "Record saved");
            table_update();
            clearFields();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "error" + ex.getMessage());
        }
                    
    }//GEN-LAST:event_btaddcheckinActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        
        txtid.setText(model.getValueAt(selectedIndex, 0).toString());
        txtname.setText(model.getValueAt(selectedIndex, 1).toString());
        txtaddress.setText(model.getValueAt(selectedIndex, 2).toString());
        txtmobile.setText(model.getValueAt(selectedIndex, 3).toString());
        txtnationality.setText(model.getValueAt(selectedIndex, 4).toString());
        cbgender.setSelectedItem(model.getValueAt(selectedIndex, 5).toString());
        txtemaill.setText(model.getValueAt(selectedIndex, 6).toString());
        jComboBox2.setSelectedItem(model.getValueAt(selectedIndex, 7).toString());
        txtRno.setText(model.getValueAt(selectedIndex, 8).toString());
        cbbed.setSelectedItem(model.getValueAt(selectedIndex, 9).toString());
        txtprice.setText(model.getValueAt(selectedIndex, 10).toString());
        
      Object dataObject = model.getValueAt(selectedIndex, 11);
       if (dataObject != null && dataObject instanceof java.util.Date){
          jDateChooser1.setDate((java.util.Date) dataObject);
      }else{
          jDateChooser1.setDate(null);
      }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
         try{
            
            String id = txtid.getText();
            String name = txtname.getText();
            String address = txtaddress.getText();
            String mobileno = txtmobile.getText();
            String nationality = txtnationality.getText();
            String gender = (String) cbgender.getSelectedItem();
            String email = txtemaill.getText();
            String roomtype = (String) jComboBox2.getSelectedItem();
            String roomno = txtRno.getText();
            String bed = (String) cbbed.getSelectedItem();
            String price = txtprice.getText();
            Date checkinDate = null;
            if (jDateChooser1.getDate() != null) {
            checkinDate = new Date(jDateChooser1.getDate().getTime());
            }
        
       controller.updateCustomer(id, name, address, mobileno, nationality, gender, email, roomtype, roomno, bed, price, checkinDate);
            JOptionPane.showMessageDialog(this, "Record updated");
            table_update();
            clearFields();
         }
         
        catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "error" + ex.getMessage());
        }
       
    }//GEN-LAST:event_btupdateActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
         try {
            String id = txtid.getText();
            controller.deleteCustomer(id);
            JOptionPane.showMessageDialog(this, "Record deleted");
            table_update();
            clearFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "error" + ex.getMessage());
        }
         
    }//GEN-LAST:event_btdeleteActionPerformed
    private void clearFields() {
        txtid.setText("");
        txtname.setText("");
        txtaddress.setText("");
        txtmobile.setText("");
        txtnationality.setText("");
        cbgender.setSelectedIndex(-1);
        txtemaill.setText("");
        jComboBox2.setSelectedIndex(-1);
        txtRno.setText("");
        cbbed.setSelectedIndex(-1);
        txtprice.setText("");
        jDateChooser1.setDate(null);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddcheckin;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox<String> cbbed;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel roomno;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemaill;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

}
