/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RoomController;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author llllllllll
 */
public class manageRooms extends javax.swing.JFrame {
   private RoomController controller;
    /**
     * Creates new form manageRooms
     */
    public manageRooms() {
        initComponents();
        controller = new RoomController();
        table_update();
    }
    
    
    public void table_update(){
       DefaultTableModel dft = (DefaultTableModel) jTable2.getModel();
        dft.setRowCount(0);
        Vector<Vector<Object>> data = controller.getAllRooms();
        for (Vector<Object> row : data) {
            dft.addRow(row);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtroomnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbroomtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbbed = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room-management1.png"))); // NOI18N
        jLabel1.setText("Manage Rooms");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close11.jpg"))); // NOI18N
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1442, 0, 51, -1));

        jTable2.setBackground(new java.awt.Color(255, 255, 153));
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 830, 592));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 106, -1, -1));

        txtroomnumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 144, 432, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 213, -1, -1));

        cbroomtype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        getContentPane().add(cbroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 244, 432, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 312, -1, -1));

        cbbed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        getContentPane().add(cbbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 343, 432, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 407, -1, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 445, 432, -1));

        btadd.setBackground(new java.awt.Color(204, 0, 0));
        btadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btadd.setForeground(new java.awt.Color(255, 255, 255));
        btadd.setText("Add Room");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, -1, -1));

        btedit.setBackground(new java.awt.Color(153, 0, 0));
        btedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btedit.setForeground(new java.awt.Color(255, 255, 255));
        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 510, 110, -1));

        btdelete.setBackground(new java.awt.Color(153, 0, 0));
        btdelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btdelete.setForeground(new java.awt.Color(255, 255, 255));
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 510, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roombk11.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1500, 1730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btcloseActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        try{
        String roomnumber,roomtype,bed,price;
        
        roomnumber=txtroomnumber.getText();
        roomtype=(String) cbroomtype.getSelectedItem();
        bed=(String) cbbed.getSelectedItem();
        price=txtprice.getText();
        
        controller.addRoom(roomnumber, roomtype, bed, price);
        JOptionPane.showMessageDialog(this, "Record saved");
        table_update();
        
        txtroomnumber.setText("");
        cbroomtype.setSelectedItem("");
        cbbed.setSelectedItem("");
        txtprice.setText("");
        txtroomnumber.requestFocus();
       
        
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"error" + ex.getMessage());
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        
        txtroomnumber.setText(model.getValueAt(selectedIndex, 0).toString());
        cbroomtype.setSelectedItem(model.getValueAt(selectedIndex, 1).toString());
        cbbed.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
        txtprice.setText(model.getValueAt(selectedIndex, 3).toString());
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
         try{
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        
        String originalroomnumber = model.getValueAt(selectedIndex, 0).toString();
             
        String roomnumber,roomtype,bed,price;
        
        roomnumber=txtroomnumber.getText();
        roomtype=(String) cbroomtype.getSelectedItem();
        bed=(String) cbbed.getSelectedItem();
        price=txtprice.getText();
        
        controller.updateRoom(roomnumber, roomtype, bed, price, originalroomnumber);
        JOptionPane.showMessageDialog(this, "Record updated");
        table_update();
        
        txtroomnumber.setText("");
        cbroomtype.setSelectedItem("");
        cbbed.setSelectedItem("");
        txtprice.setText("");
        txtroomnumber.requestFocus();
       
        
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"error" + ex.getMessage());
        }
        
    }//GEN-LAST:event_bteditActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
         try{
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        
        String originalroomnumber = model.getValueAt(selectedIndex, 0).toString();
            
        
        controller.deleteRoom(originalroomnumber);
        JOptionPane.showMessageDialog(this, "Record deleted");
        table_update();
        
        txtroomnumber.setText("");
        cbroomtype.setSelectedItem("");
        cbbed.setSelectedItem("");
        txtprice.setText("");
        txtroomnumber.requestFocus();
       
        
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"error" + ex.getMessage());
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JComboBox<String> cbbed;
    private javax.swing.JComboBox<String> cbroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomnumber;
    // End of variables declaration//GEN-END:variables
}
